name: "Setup Environment"
description: "Create Conda environment for a GitHub Actions Job"

runs:
  using: "composite"
  steps:
    - uses: mamba-org/setup-micromamba@v2
      env:
        # Increase this value to reset cache if conda-lock.yml has not changed
        CACHE_NUMBER: 0
      with:
        environment-file: conda-lock.yml
        environment-name: locked-env
        # only cache environment
        cache-environment: true
        cache-downloads: false
        cache-environment-key: ${{ runner.os }}-conda-environment-${{ env.CACHE_NUMBER }}-${{ hashFiles('conda-lock.yml') }}
