name: Test
on: [push]
jobs:
  test-build-env:
    runs-on: ubuntu-latest    
    defaults:
      run:
        # Ensure conda env is activated
        shell: "bash -l {0}"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-environment
      - run: echo $PATH
      - run: which python3
      - run: python -c "import numpy; print(numpy.__version__)"
